version: 0.1
phases:
  install:
    commands:
      - pwd
      - ls -lrt
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket parth-pipeline-bucket-1 --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml
