version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket parth-pipeline-bucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml