version: 0.2

phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip handler.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name crewinfolambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"