version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket codepipeline-ap-south-1-597145927771 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml